# Generated by Django 3.2.7 on 2021-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=25)),
                ('condition', models.CharField(max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
                ('borrowed_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('borrowed_since', models.TextField(blank=True, null=True)),
                ('estimated_replacement_cost', models.PositiveIntegerField()),
            ],
        ),
    ]
